interface PickListValuesAssociationsResponseHandler{

}
export type{
	PickListValuesAssociationsResponseHandler as MasterModel,
	PickListValuesAssociationsResponseHandler as PickListValuesAssociationsResponseHandler
}
